# services:
#   web:
#     build: .
#     container_name: herveob-cv
#     command: yarn start
#     volumes:
#       - '.:/usr/src/app'
#       - '/usr/src/app/node_modules'
#     ports:
#       - "3000:3000"
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     stdin_open: true